name: PPPhotography
favicon: null
layout_spectrum: 0.62779
typography_spectrum: 0.75654
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#050503'
    - '#005e60'
    - '#d8b3a3'
    - '#6ee9eb'
    - '#876c61'
  brandStrength: 0.7690586030948907
  lightness: 0.356139991665259
  saturation: 0.14313626429066062
  rhythmicContrast: 0.6857551035936922
purpose: []
